= Quarkus OAuth2/OIDC Proxy for NGINX
:toc: left
:icons: font
:source-highlighter: highlight.js

== Overview
This Quarkus application provides OAuth2/OpenID Connect authentication for NGINX, leveraging a stateless cookie-based approach to ensure secure and scalable authentication without relying on server-side sessions.

=== REST Endpoints

* */auth/login*: Initiates the OpenID Connect (OIDC) authentication flow.
* */auth/callback*: Processes the response from the Identity Provider (IDP) and generates the authentication cookie.
* */auth/validate*: Verifies the token from the authentication cookie (used by NGINX via the `auth_request` directive).
* */auth/logout*: Deletes the authentication cookie to log the user out.
* */auth/.well-known/jwks.json*: Provides the Json Web Key Set for the tokens passed to the backend.

=== NGINX Integration

The provided NGINX configuration leverages the `auth_request` directive to authenticate requests against the `/auth/validate` endpoint. It forwards the validated JWT token to backend services for further processing.

== Provider Compatibility

The application works with any OAuth2/OpenID Connect provider by setting the appropriate configuration in `application.yaml`. The design is completely stateless, storing all authentication information in cookies without using server-side sessions.

To configure for a specific provider (like Google, EntraID, etc.), you only need to update the OIDC configuration variables in the YAML file or set the corresponding environment variables.

== Configuration

include::docs/config.adoc[leveloffset=+2]

== Generate Private and Public Keys

=== Generate ES256 Keys

[source, bash]
----
openssl ecparam -genkey -name prime256v1 -noout -out private_key.pem
openssl pkcs8 -topk8 -inform PEM -outform PEM -in private_key.pem -out private_key_pkcs8.pem -nocrypt
openssl ec -in private_key.pem -pubout -out public_key.pem
cat private_key_pkcs8.pem
cat public_key.pem
----