quarkus:
  http:
    port: 8080

#  oidc:
#    authentication:
#      redirect-path: /auth/callback
#      restore-path-after-redirect: false
#    logout:
#      post-logout-path: /
  log:
    level: INFO
    category:
      "io.github.renegrob.oidc":
        level: ${OIDC_LOG_LEVEL:DEBUG}
