apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-client-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  OIDC_FEDERATED_IDP_CLIENT_ID: {{ required "The idp.client.id value is required!" .Values.idp.client.id }}
  OIDC_FEDERATED_IDP_CLIENT_SECRET: {{ required "The idp.client.secret value is required!" .Values.idp.client.secret }}
  OIDC_FEDERATED_IDP_CLIENT_STATE_SECRET: {{ required "The idp.client.stateSecret value is required!" .Values.idp.client.stateSecret }}
  OIDC_COOKIE_ENCRYPTION_KEY: {{ required "The cookie.encryption.key value is required!" .Values.cookie.encryption.key }}
