apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-client-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
immutable: true
stringData:
  OIDC_FEDERATED_IDP_CLIENT_ID: {{ required "The idp.client.clientId value is required!" .Values.idp.client.clientId }}
  OIDC_FEDERATED_IDP_CLIENT_SECRET: {{ required "The idp.client.clientSecret value is required!" .Values.idp.client.clientSecret }}
  OIDC_FEDERATED_IDP_CLIENT_STATE_SECRET: {{ required "The idp.client.stateSecret value is required!" .Values.idp.client.stateSecret }}
