apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-env-config
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{ with .Values.cookie }}
  {{- if .name }}OIDC_COOKIE_NAME: {{ .name | quote }}
  {{ end }}
  {{- if .path }}OIDC_COOKIE_PATH: {{ .path | quote }}
  {{- end }}
  OIDC_COOKIE_DOMAIN: {{ required ".cookie.domain is required." .domain | quote }}
  {{ if .secure }}OIDC_COOKIE_SECURE: {{ .secure | quote }}
  {{ end }}
  {{- if .httpOnly }}OIDC_COOKIE_HTTP_ONLY: {{ .httpOnly | quote }}
  {{ end }}
  {{- if .sameSite }}OIDC_COOKIE_SAME_SITE: {{ .sameSite | quote }}
  {{ end }}
  {{- if .maxAge }}OIDC_COOKIE_MAX_AGE: {{ .maxAge | quote }}
  {{ end }}
  {{- end }}
  {{- with .Values.token }}
  {{- if .headerName }}OIDC_TOKEN_HEADER_NAME: {{ .headerName | quote }}
  {{ end }}
  {{- if .forwardingMethod }}OIDC_TOKEN_FORWARDING_METHOD: {{ .forwardingMethod | quote }}
  {{ end }}
  {{- end }}
  {{- with .Values.idp }}
  {{- if .federationMode }}OIDC_FEDERATION_MODE: {{ .federationMode | quote }}
  {{ end }}
  {{- if .discoveryEnabled }}OIDC_FEDERATED_IDP_DISCOVERY_ENABLED: {{ .discoveryEnabled | quote }}
  {{ end }}
  {{- if .authServerUrl }}OIDC_FEDERATED_IDP_AUTH_SERVER_URL: {{ .authServerUrl | quote }}
  {{ end }}
  {{- if .tokenPath }}OIDC_FEDERATED_IDP_TOKEN_PATH: {{ .tokenPath | quote }}
  {{ end }}
  {{- if .userinfoUrl }}OIDC_FEDERATED_IDP_USERINFO_PATH: {{ .userinfoUrl | quote }}
  {{ end }}
  {{- if .jwksPath }}OIDC_FEDERATED_IDP_JWKS_PATH: {{ .jwksPath | quote }}
  {{ end }}
  {{- if .logoutUrl }}OIDC_FEDERATED_IDP_END_SESSION_PATH: {{ .logoutUrl | quote }}
  {{ end }}
  {{- if .issuer }}OIDC_FEDERATED_IDP_ISSUER: {{ .issuer | quote }}
  {{ end }}
  {{- if .audience }}OIDC_FEDERATED_IDP_AUDIENCE: {{ .audience | quote }}
  {{- end }}
  {{- with .client }}
  OIDC_FEDERATED_IDP_CLIENT_REDIRECT_URI: {{ required ".idp.client.redirectUrl is required." .redirectUrl | quote }}
  {{ if .scope }}OIDC_FEDERATED_IDP_CLIENT_SCOPE: {{ .scope | quote }}
  {{- end }}
  {{ if .pckeMethod }}OIDC_FEDERATED_IDP_CLIENT_PKCE_METHOD: {{ .pckeMethod | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.internalIssuer }}
  OIDC_INTERNAL_ISSUER_ISSUER: {{ required ".Values.internalIssuer.issuer is required." .issuer | quote }}
  {{ if .audience }}OIDC_INTERNAL_ISSUER_AUDIENCE: {{ .audience | quote }}
  {{ end }}
  {{- if .expiration }}OIDC_INTERNAL_ISSUER_EXPIRATION: {{ .expiration | quote }}
  {{ end }}
  {{- if .scope }}OIDC_INTERNAL_ISSUER_SCOPE: {{ .scope | quote }}
  {{ end }}
  {{- end }}
