apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-issuer-keys
type: Opaque
data:
  private-key.pem: {{ .Values.internalIssuer.keys.privateKey | b64enc }}
  public-key.pem: {{ .Values.internalIssuer.keys.publicKey | b64enc }}
